export default {
  ALERT_HEIGHT: 30,
  AVATAR_WIDTH: 120,
  BUTTON_HEIGHT: 64,
  DEADZONE_HEIGHT: 235,
  DOT_WIDTH: 4,
  LOGO_WIDTH: 350,
  LOGO_HEIGHT: 320,
  PROFILE_CONTAINER_HEIGHT: 72
} as const;
